apiVersion: v1
entries:
  hello:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-02-19T22:37:16.35629884Z"
    description: A Helm chart for Kubernetes
    digest: a8b00822f112c659147ddfab8b27834f9bf09cac0e3eee5fd2845504c1f120ab
    name: hello
    type: application
    urls:
    - https://raw.githubusercontent.com/MohitMajhi/k8s/main/helm/hello-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-19T22:37:16.355591741Z"
