apiVersion: v1
entries:
  hello:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-02-19T22:57:49.475179973Z"
    description: A Helm chart for Kubernetes
    digest: a8b00822f112c659147ddfab8b27834f9bf09cac0e3eee5fd2845504c1f120ab
    name: hello
    type: application
    urls:
    - https://raw.githubusercontent.com/MohitMajhi/k8s/main/helm/hello-0.1.0.tgz
    version: 0.1.0
  hello-pod:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-02-19T22:57:49.476044871Z"
    description: A Helm chart for Kubernetes
    digest: d3793b4f6146e98a927981731fb1a11683308d62eb821f77a9d7900e28d3cc41
    name: hello-pod
    type: application
    urls:
    - https://raw.githubusercontent.com/MohitMajhi/k8s/main/helm/hello-pod-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-19T22:57:49.472853778Z"
